"""adiciona eventos inscricoes e certificados

Revision ID: a7ce03e374ab
Revises: 7a5194da24b3
Create Date: 2026-09-13 13:37:47.873491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ce03e374ab'
down_revision: Union[str, Sequence[str], None] = '7a5194da24b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscricoes_id'), 'inscricoes', ['id'], unique=False)
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscricao_id', sa.Integer(), nullable=False),
    sa.Column('codigo_validacao', sa.String(length=50), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inscricao_id'], ['inscricoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_validacao'),
    sa.UniqueConstraint('inscricao_id')
    )
    op.create_index(op.f('ix_certificados_id'), 'certificados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificados_id'), table_name='certificados')
    op.drop_table('certificados')
    op.drop_index(op.f('ix_inscricoes_id'), table_name='inscricoes')
    op.drop_table('inscricoes')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
